import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";

const outfit = Outfit({
    variable: "--font-outfit",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${outfit.class}`}>
                <Navbar />
                <main className="w-10/12 mx-auto">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
